export const wildlandsText = `
<b>The Wildlands</b> are an untamed frontier where nature grows fierce and ancient magic lingers in the air. Dense forests, jagged cliffs, and mist-covered valleys stretch for miles, untouched by civilization. Strange flora and dangerous beasts thrive here, many shaped by the wild energy that permeates the land. Adventurers from every corner of the realm travel to the Wildlands seeking experience, glory, and rare resources. Monsters of all ranks roam freely — from aggressive wildlife to corrupted spirits and towering elemental beasts. Those who survive the hunt grow stronger, earning both skill and reputation. Despite its dangers, the Wildlands are filled with hidden rewards: enchanted springs that restore strength, ruins of forgotten kingdoms, and treasures guarded by ancient guardians. Camps and outposts act as brief safe havens, but no one truly tames this land. A proving ground for the brave and reckless alike, the Wildlands are where legends begin — and where many fall.
`;

export const questText = `
<b>The Stalwart Hall</b> is a bustling haven for adventurers from all corners of the realm. Within its sturdy stone walls, heroes can rest and recover, enjoy hearty meals and frothy drinks, and share tales of daring exploits. The hall offers a variety of quests, from simple errands to perilous journeys, giving every adventurer a chance to prove their skill and earn fortune. Here, one might meet future party members, forge lasting bonds, or encounter rival adventurers and cunning foes. The Stalwart Hall hums with energy, camaraderie, and the occasional clash of steel, serving as both a sanctuary and a launching point for the next great adventure.
`;

export const marketText = `
<b>The Shimmering Market</b> is a vibrant hub where adventurers and locals alike gather to buy, trade, and prepare for the perils of the wild. Stalls glint with enchanted weapons, sturdy armor, rare trinkets, and essential provisions for long journeys. Merchants call out their wares, offering both practical gear and curiosities that catch the eye. The aroma of freshly baked bread, roasted meats, and exotic spices fills the air, inviting weary travelers to pause and refuel. Here, heroes can equip themselves for the next quest, overhear rumors of distant lands, or encounter fellow adventurers—friends or rivals alike. The market buzzes with life, deals, and occasional intrigue, making it a place where preparation and adventure meet in equal measure.
`;

